### ISSUE TITLE
Infinite loading on title

### ISSUE THREAD

**Issue by YnwLNE** [EyezahMC/Cosmetica#26]
Not sure what causes this because there is no crash log to go off of. I will, however, provide my modlist 
Fabric 13.3, 1.18.1
https://pastebin.com/k74M5Ar8

**Comment by valoeghese** [comment]
Can you provide the latest.log for this run? I suspect the error is being suppressed

**Comment by SquidOrigins** [comment]
Fabric Capes Mod Crashes Cosmetica Remove that and it will fix the issue

**Comment by YnwLNE** [comment]
Removing FC did work. ty
