### ISSUE TITLE
Will there/is there anyway to disable the cape so i can see my paid for OptiFine cape? 

### ISSUE THREAD

**Issue by NoahCorke** [EyezahMC/Cosmetica#27]
Will there/is there anyway to disable the cosmetica cape so i can see my paid for OptiFine cape? Thank you!!!!!!!!!! :D!!!!!!!!!!

**Comment by valoeghese** [comment]
You can remove your cosmetica cape on the website (go to "cosmetica settings" -> "customise cosmetics" in the mod, and click "use no cape").

Then, go to your cape server settings on the website and set "optifine" to "show"

**Comment by NoahCorke** [comment]
Sorry I'm still a bit confused as you worded this in a confusing way, do you mind re-explaining?

**Comment by NoahCorke** [comment]
> You can remove your cosmetica cape on the website (go to "cosmetica settings" -> "customise cosmetics" in the mod, and click "use no cape").
> 
> Then, go to your cape server settings on the website and set "optifine" to "show"

Sorry I'm still a bit confused as you worded this in a confusing way, do you mind re-explaining?

**Comment by eyezahhhh** [comment]
If you don't know how to sign into the Cosmetica website check the instructions on our Curseforge or Modrinth pages.

Once you're logged in, make sure you don't have a cape set using Cosmetica, you can make sure of this by clicking the "Use no cape" button on your profile page.

If you've done that and you see an Optifine cape that says "NO" on your back, scroll to the bottom of the website and click the link that says "cape settings" in the footer. From there you can set Optifine capes to "show" and click save.

Finally click "reload cosmetics" in-game for your changes to take effect.

**Comment by NoahCorke** [comment]
i've been able to do it :D, i was just being a bit silly dumb sorry!!!!!!!!!! :D :D :D :D <3 <3 <3<3 :):):):)!!!!!!!!!!
