### ISSUE TITLE
Problem beim verbinden mit dem Cosmetica Server

### ISSUE THREAD

**Issue by GlitchHub16** [EyezahMC/Cosmetica#29]
Ich habe mir Cosmetica heruntergeladen und alles hat funktioniert bis ich mich mit den Cosmetica Servern verbinden wollte da steht das ich keine Internetverbindung habe oder einen cracked Minecraft Account disem (denke) ich habe ich nicht. Wie sehe ich denn das ich einen cracked Account habe. Falls es hilft hier meine Version: 1.18.1 Fabric

**Comment by valoeghese** [comment]
Wir sind uns diesem Fehler schon bewusst und versuchen im nächsten Update ihn zu beheben

**Comment by eyezahhhh** [comment]
Fixed in version [1.1.1](https://cosmetica.cc/join).
