### ISSUE TITLE
Question:Is this compatible with optifine?

### ISSUE THREAD

**Issue by zeldaking** [EyezahMC/Cosmetica#31]

**Comment by zeldaking** [comment]
Title says it all.

**Comment by craftish37** [comment]
> **Get Cosmetica capes working on Optifine**
> To add partial Cosmetica support to a bunch of clients.
> https://www.arccapes.com/install.html
> Using this method the capes you'll be displayed **will not** respect your cape settings. It uses default settings with the exception of Optifine capes which are shown. We're working on an alternative method to this that you'll be able to use and have more control over what cosmetics you see.
Eyezah on discord yesterday

So I think this is a good anwser (:

**Comment by eyezahhhh** [comment]
The Cosmetica mod itself is also compatible with Optifne! You'll just need to use OptiFabric seeing as we don't yet have a Forge mod.
