### ISSUE TITLE
1.18 Premium Account Can't Connect To Youre Services

### ISSUE THREAD

**Issue by Commandthealien** [EyezahMC/Cosmetica#33]
I Get The Can't Authenticate Account And I Have Great Internet And Have A Premiumn Account And AM Using 1.18 Version Of Cosmetica

**Comment by valoeghese** [comment]
Duplicate of #29, known issue that happens occasionally

**Comment by eyezahhhh** [comment]
Fixed in version [1.1.1](https://cosmetica.cc/join).
