### ISSUE TITLE
Rendering user with cape doesn't work

### ISSUE THREAD

**Issue by Videry** [EyezahMC/Cosmetica#34]
On mobile devices, when you open any kind of cosmetic and browse throught them, the cosmetics at the start of the page don't render, and you have to open it to see what it looks like

**Comment by Videry** [comment]
![Screenshot_20220430_103447_com android chrome](https://user-images.githubusercontent.com/76826079/166109936-8e58908c-c9dc-4e31-b690-33361fc808f4.jpg)
![Screenshot_20220430_103453_com android chrome](https://user-images.githubusercontent.com/76826079/166109937-ddbe0693-8d93-4967-ae68-850f4bf1bf16.jpg)
![Screenshot_20220430_103457_com android chrome](https://user-images.githubusercontent.com/76826079/166109938-e5607002-6531-4786-a188-d827123e981d.jpg)
![Screenshot_20220430_103507_com android chrome](https://user-images.githubusercontent.com/76826079/166109939-40f36bbd-2855-4567-8952-b3cd20285acc.jpg)
![Screenshot_20220430_103520_com android chrome](https://user-images.githubusercontent.com/76826079/166109940-f717d5fc-9f07-4d74-b8dd-69b0ca8c44ba.jpg)

**Comment by eyezahhhh** [comment]
We're aware of the issue and should have it fixed in the next explore page update.

**Comment by eyezahhhh** [comment]
In the latest website update this seems to have been fixed (I've reduced page size from 16 cosmetics to 8) with the exception of the Top Creators page, which I still get the issue on. I'll need to do some further testing but now most of the website works on mobile.

Will close this issue once Top Creators page is fixed.

**Comment by valoeghese** [comment]
is this fixed?

**Comment by eyezahhhh** [comment]
Looks like many mobile devices limit the number of 3d instances you can have at once to 8. So I capped the leaderboard to 8 players when you're on mobile.
