### ISSUE TITLE
Non-hat components

### ISSUE THREAD

**Issue by Madis0** [EyezahMC/Cosmetica#41]
Bedrock has an extensive way to edit the user's model, so for this to be more than just a hat layer, maybe consider modelling other body parts as well?

**Comment by valoeghese** [comment]
We already have shoulder buddies, and back bling will be added in the next major update ;)

**Comment by Madis0** [comment]
Good to know, though I was also thinking boots, watches, chains etc. You could probably have a look at Bedrock's Marketplace and see what people buy the most 😅

**Comment by valoeghese** [comment]
will close this when 1.2.0 is released since by then we'll have both back bling and double shoulder buddies so will definitely have quite a few "non-hat components." Shoulder Buddies are should be useable as armwear as well once we add the toggle to upload to make the sb swing with your arm

**Comment by eyezahhhh** [comment]
Released in [1.2.0](https://cosmetica.cc/join).
