### ISSUE TITLE
Immediate crashes, potential mod conflict (Fabric)

### ISSUE THREAD

**Issue by dark-fedora** [EyezahMC/Cosmetica#42]
### Description
Minecraft exits with code -1 when launching this mod with a particular list of other mods. Look below for an additional list.

### Execution
Launch Minecraft Fabric 1.18.2 with the list of following mods. I have uploaded the latest.log to pastebin here: https://pastebin.com/qk511q7F

### Comments
I've noticed Sodium having unexpected bugs recently, for example freezing rendering threads if you enter a world when you would be shown the "You died!" screen upon joining. Iris/Indium are also rendering engine changes, and could potentially be interacting in some negative way.
CustomPlayerModels is not very widely used, so it's another potential culprit.
The large number of "tweak" mods mostly just fix noted bugs on the Minecraft bug list.

### Setup
 - OS: Windows 10
 - Minecraft Fabric, 1.18.2

### Additional Mods

```
antighost-1.18.2-fabric0.47.10-1.1.4.jar
BetterF3-1.2.4-Forge-1.18.2.jar
Blanket Client tweaks-1.0.3.jar
blur-2.4.1.jar
brb-1.18.2-forge-1.5.6.jar
charmonium-fabric-1.18-4.0.0.jar
cloth-config-6.2.57-fabric.jar
continuity-1.1.0+1.18.2.jar
CustomPlayerModels-Fabric-1.18-0.3.1a.jar
enchantment-lore-1.2.6-1+MC1.18-1.18.2.jar
fabric-api-0.51.1+1.18.2.jar
get-current-song-1.0.1.jar
IKnowWhatImDoing-4.0.0-fabric.jar
indium-1.0.3+mc1.18.2.jar
iris-mc1.18.2-1.2.4-build.38.jar
lithium-fabric-mc1.18.2-0.7.9.jar
make_bubbles_pop-0.0.1-1.18.2.jar
modmenu-3.2.1.jar
okzoomer-5.0.0-beta.6+1.18.2.jar
phosphor-fabric-mc1.18.x-0.8.1 (1).jar
PresenceFootsteps-1.5.0.jar
qsl-1.1.0-beta.8_qfapi-1.0.0-beta.13_fapi-0.51.1_mc-1.18.2.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
Void-Fog-2.6.2.jar
whyamionfire-1.1.2.jar
XaerosWorldMap_1.21.2_Fabric_1.18.2.jar
```

**Comment by eyezahhhh** [comment]
Looks like Cosmetica isn't compatible with CPM, remove one of the two (we'll try make them compatible in future if it isn't _loads_ of work).

We don't do much with rendering, Cosmetica uses standard Minecraft model formats and thus Minecraft codebase renders it for us, Sodium and Iris appear to be fully compatible with Cosmetica.

I'll close this and add CPM to our incompatible mods list, but as a general rule of thumb: If your game is crashing and you have Cosmetica and another player model/cape manipulating mod, there's a good chance the two aren't compatible.
