### ISSUE TITLE
Immediate clean crash upon joining a world

### ISSUE THREAD

**Issue by lxly9** [EyezahMC/Cosmetica#46]
**Description:**
Minecraft starts fine but when I try to enter a world it jumps from loading terrain to saving world and quits Minecraft completely.

**Steps:**
Start game with Fabric client 1.18.1 and the following mods and enter any world: 
[error.txt](https://github.com/EyezahMC/Cosmetica/files/8732020/error.txt)

**Setup:**
- OS: Windows 11
- Minecraft Fabric, 1.18.1

**Additional context**
I have 128 client mods installed. Dashloader also gives an error message shortly after loading into the game when the fabric capes mod is installed.

**Comment by lxly9** [comment]
It is the essential mod. I forgot it adds cosmetics to the game!

**Comment by craftish37** [comment]
It isn’t, I play with both 👀
