### ISSUE TITLE
Cape Client link does not work

### ISSUE THREAD

**Issue by DelofJ** [EyezahMC/Cosmetica#47]
**Describe the bug**
On https://cosmetica.cc/join , the Cape Client Install button does not work, it redirects to the old site https://www.arccapes.com/install.html which does no longer exist

**To Reproduce**
1. Go to 'https://cosmetica.cc/join'
2. Click on 'Install' in 'Cape Client'
3. See error

**Expected behavior**
The website should work

**Comment by craftish37** [comment]
Arccapes is down if not dead sir

**Comment by DelofJ** [comment]
And you can't remake a page to install the Cape Client like it was on Arccapes ?

**Comment by eyezahhhh** [comment]
Arc is gone forever, I'll put the instructions up on the Cosmetica website and change the link.

I'll close this when that's all done.
