### ISSUE TITLE
Infinite Loading/Splash Screen?

### ISSUE THREAD

**Issue by zaxiify** [EyezahMC/Cosmetica#48]
**Describe the bug**
When I start up the game with Cosmetica in my mods folder, the game loops the splash screen,

**To Reproduce**
1. Open Minecraft
2. Get the infinite splash screen

**Expected behavior**
Game loads up, and I can play.

**Screenshots**

It just loops this.

![image](https://user-images.githubusercontent.com/36055611/169718469-a65a8e90-70d4-4de3-a630-cf3cdf1b1225.png)

**Setup (please complete the following information):**
 - OS: Win 11
 - MC Ver: 1.18.2
 - Fabric Ver: 0.14.6
 - Version: 1.1.1

**Comment by eyezahhhh** [comment]
Please post your mods list

**Comment by zaxiify** [comment]
Here ya go:

- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- advancementinfo 1.18.2-fabric0.47.10-1.3.1
	- animatica 0.4+1.18
	- antighost 1.18.2-fabric0.47.10-1.1.4
	- auudio 1.0.3
	- baritone 1.18.2-SNAPSHOT via mathax
	- betterf3 1.2.5
	- bsvsb 2.0.5
	- caffeineconfig 1.1.0 via sodium-extra
	- capes 1.3.1+1.18.2
	- cem 0.7.1
	- citresewn 1.0.1+1.18.2
	- citresewn-defaults 1.0.1+1.18.2 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62 via betterf3
	- colormatic 3.1.1+mc.1.18.2
	- com_github_llamalad7_mixinextras 0.0.9 via cull-less-leaves
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- completeconfig 1.0.0 via cem
	- continuity 1.1.0+1.18.2
	- controlling 9.0+19
	- crowdin-translate 1.4+1.18.2 via antighost
	- cull-less-leaves 1.0.1
	- cullleaves 2.3.2
	- drippyloadingscreen 1.6.1
	- dynamicfps 2.1.0
	- enhancedblockentities 0.6+1.18.2
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via sodium-extra
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via betterf3
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.14.6
	- farsight 1.18-1.9
	- fastchest 1.2+1.18
	- ferritecore 4.2.1
	- indium 1.0.3+mc1.18.2
	- iris 1.2.4-build.38
	- java 17
	- konkrete 1.3.3
	- lambdynlights 2.1.0+1.17
	- lazy-language-loader 0.3.0
	- lazydfu 0.1.2
	- lithium 0.7.10
	- logical_zoom 0.0.14
	- mathax 1.7.6
	- midnightlib 0.4.0
	- minecraft 1.18.2
	- modmenu 3.2.2
	- mousetweaks 2.22
	- notenoughcrashes 4.1.6+1.18.2
	- noweathereffects 1.3.0
	- omega-config 1.2.3-1.18.1 via capes
	- optigui 1.0.4
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_commons_commons-text 1.9 via optigui
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- pride 1.1.0+1.17 via lambdynlights
	- puzzle 1.2.1
	- puzzle-base 1.2.1 via puzzle
	- puzzle-gui 1.2.1 via puzzle
	- puzzle-models 1.2.1 via puzzle
	- puzzle-splashscreen 1.2.1 via puzzle
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.4+mc1.18.2-build.39
	- spruceui 3.3.0+1.17 via enhancedblockentities
	- starlight 1.0.2+fabric.89b8d9f
	- tooltipfix 1.0.4-1.18

**Comment by eyezahhhh** [comment]
You have the capes mod, remove that and it should work. #42 

I really need to make an incompatible mods list.

**Comment by zaxiify** [comment]
Ok, tysm!!

**Comment by zaxiify** [comment]
This didn't work, do you might have any more fixes?

**Comment by zaxiify** [comment]
Nevermind, the mod wasn't deleting for some reason. Thank you for your help!
