### ISSUE TITLE
Not being able to launch

### ISSUE THREAD

**Issue by MrPurpz** [EyezahMC/Cosmetica#52]
Whenever I try to launch the mod on 1.19 it keeps repeating the Mojang loading screen. It could be the current mods I am using (mods attached)
![Screenshot 2022-06-25 180526](https://user-images.githubusercontent.com/108200228/175793015-17e1daed-39a9-4c3d-883c-b44ed1afc94a.png)
![Screenshot 2022-06-25 180501](https://user-images.githubusercontent.com/108200228/175793016-e8329381-4808-4d60-8539-49e2f207e7ad.png)

**Comment by eyezahhhh** [comment]
You have another capes mod (Fabric Capes?). Remove that and try again.

**Comment by MrPurpz** [comment]
I got it working but I was just wondering how do I change the cosmetics?

**Comment by MrPurpz** [comment]
wait nvm
