### ISSUE TITLE
my player is upside down

### ISSUE THREAD

**Issue by AbsolutedWeirdo** [EyezahMC/Cosmetica#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. Windows 10, iOS]
 - Minecraft Version [e.g. chrome, safari]

**Additional context**

**Comment by eyezahhhh** [comment]
This is a feature of "Region-Specific Effects" for Australians. You can disable regional effects in the mod settings.
