### ISSUE TITLE
Cosmetics not rendering in Inventory with Iris 1.2.6 - 1.19

### ISSUE THREAD

**Issue by AlitaTeal** [EyezahMC/Cosmetica#54]
**Describe the bug**
Character preview in the inventory (survival and creative) doesn't render your cosmetics, instead it makes the parts of the player they cover invisible. Happens on both hats and shoulder buddies. Capes and elytras are rendering normally. Third person view shows all cosmetics being rendered properly as well.

**To Reproduce**
1. Open inventory

**Screenshots**
![2022-07-27_22 08 04](https://user-images.githubusercontent.com/10361655/181245840-12350111-1b81-4caa-ac33-1bafd2de26fe.png)
![2022-07-27_22 08 16](https://user-images.githubusercontent.com/10361655/181245845-c71d45a1-9e43-4165-a85b-12a7c06a45f2.png)

**Setup (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19
 - Fabric Loader 0.14.8
 - Fabric API 0.58.0
 - Sodium 0.4.2 Build 16
 - Iris 1.2.6

**Additional context**
Character preview background changed to more clearly show bug.

**Comment by valoeghese** [comment]
That's unusual, I haven't had this bug before. Does it only happen as of Iris 1.2.6?

**Comment by AlitaTeal** [comment]
Yeah, only in 1.2.6. Renders just fine with 1.2.5 and the same versions of Fabric/Sodium.

**Comment by eyezahhhh** [comment]
Fixed in next version
