### ISSUE TITLE
[1.19.1] Fabric crash on startup

### ISSUE THREAD

**Issue by Enchanted-Games** [EyezahMC/Cosmetica#55]
**Describe the bug**
Starting the game with this mod installed causes the game to crash

**To Reproduce**
1. Put this mod and fabric api in the mods folder
2. Run the game
3. Game crashes while trying to load cosmetica

**Expected behavior**
The game doesn't crash with cosmetica installed

**Setup (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.19.1
 - Version: 1.1.1

**Additional context**
Latest log
[latest.log](https://github.com/EyezahMC/Cosmetica/files/9229938/latest.log)

**Comment by eyezahhhh** [comment]
Cosmetica has not been released for Minecraft 1.19.1, will likely release tonight.

(Will close when released)

**Comment by Enchanted-Games** [comment]
ah alright

**Comment by lukasong** [comment]
Seems like the latest 1.19.1 build for Fabric still crashes on startup.

**Comment by eyezahhhh** [comment]
Can you post mod list and log?

**Comment by lukasong** [comment]
Minecraft Log: https://pastebin.com/hqvCZpMR
Mod List: https://pastebin.com/weSug6KN

Fabric 0.14.8

**Comment by eyezahhhh** [comment]
Uninstall Fabric Capes

**Comment by lukasong** [comment]
That fixed it, and the cape selection in the mod itself is nice (and most importantly works with wavey capes). Thanks for the help!
