### ISSUE TITLE
Cosmetica 1.2.0 Crash on Startup w/ All of Fabric 5

### ISSUE THREAD

**Issue by bassistracer** [EyezahMC/Cosmetica#56]
**Describe the bug**
Minecraft crashes on start up with exit code 1 on boot. Strangely, the version before this one works just fine.

**To Reproduce**
1. Download All of Fabric 5 (modpack)
2. Add in Cosmetica

**Additional context**
Not exactly sure if full-on modpacks are supported, I know you generally have to isolate the mod that's causing the problem, but I'm maybe wondering of the error log reported here might help narrow it down for anyone who's good at reading it.
https://mclo.gs/VNgQaUA

**Comment by eyezahhhh** [comment]
It looks like your errors are caused by "tlcosmetica via visuality", what happens if you remove Visuality?

**Comment by bassistracer** [comment]
> It looks like your errors are caused by "tlcosmetica via visuality", what happens if you remove Visuality?

Ah heck, sorry for being so late. Removing Visuality seemed to fix the issue, thanks!
