### ISSUE TITLE
"Fixed to torso" in shoulder buddies browsing 

### ISSUE THREAD

**Issue by lordofthecarrots** [EyezahMC/Cosmetica#57]
On the [shoulder buddies browsing page](https://cosmetica.cc/shoulderbuddies#1), cosmetics that have "fixed to torso" disabled show up as fixed to the torso. Its all fine on the actual cosmetic page however it makes the cosmetics on the browsing page look a bit naff.

![image](https://user-images.githubusercontent.com/77242951/188908865-9a57bf67-1e11-4e95-883c-5f9514ae86e6.png)
![image](https://user-images.githubusercontent.com/77242951/188909017-9cafeca7-b2f6-4912-9506-2da9c431daf1.png)
![image](https://user-images.githubusercontent.com/77242951/188909041-474dce25-4894-4cf0-955c-f7916549dca2.png)

**Comment by eyezahhhh** [comment]
Fixed
