### ISSUE TITLE
Arcmetica shoulder buddies off centre when not "fixed to torso"

### ISSUE THREAD

**Issue by lordofthecarrots** [EyezahMC/Cosmetica#63]
While running optifine (I tested this on both default and sol client) and using arcmetica, shoulder buddies that have "fixed to torso" disabled are off centre ingame (as you can seen in the first screenshot). 

![image](https://user-images.githubusercontent.com/77242951/191366095-91898a59-3e88-4a67-9f8e-fa2a9167c696.png)
*In game

![image](https://user-images.githubusercontent.com/77242951/191366323-af08d332-e346-4b62-bbc3-a5a2729c71ca.png)
*how it should be

**Comment by eyezahhhh** [comment]
Should be fixed, reopen if not.
