### ISSUE TITLE
Hat not letting me allow with helmet when I create on website

### ISSUE THREAD

**Issue by DrakonTide** [EyezahMC/Cosmetica#66]
Whenever I try to upload my hat, Bathypelagic dragon head, to the website with allow with helmet on it always unchecks it after its been approved. I have tried to upload it twice now and neither time did it save that it works when a helmet is on.

**Comment by eyezahhhh** [comment]
That's because our staff can change those properties.

We don't let hats be shown with helmets if the hat would conceal the helmet.

For support regarding specific cosmetics, feel free to ask in our Discord server https://cosmetica.cc/discord
